name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./aplicacao

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Build
        run: docker-compose up --build -d
  
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reset do Banco
        run: docker-compose run app rails db:reset
      - name: Rodando os testes
        run: docker-compose run app rspec
        
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: docker-compose run app bash -c "gem install rubocop; rubocop -A --fail-level F"
